<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { api } from './api';
import { useAuth } from './stores/auth';
const auth=useAuth(), stats=ref<any>(), range=ref<any>(), challenges=ref<any[]>([]), events=ref<any[]>([]), ranking=ref<any[]>([]), error=ref('');
const category:any={WEB:'网页安全',CRYPTO:'密码学',NETWORK:'网络分析',REVERSE:'逆向工程',PWN:'二进制安全'};
const greeting=computed(()=>auth.user?`${auth.user.username}，继续你的训练`:'从下一道题开始训练');
const nextTasks=computed(()=>challenges.value.filter(item=>!item.solved&&item.available!==false).slice(0,3));
onMounted(async()=>{try{const [s,r,c,e,b]=await Promise.all([api<any>('/dashboard/stats'),api<any>('/range/overview'),api<any[]>('/challenges'),api<any[]>('/dashboard/events'),api<any[]>('/leaderboard')]);stats.value=s;range.value=r;challenges.value=c;events.value=e;ranking.value=b;}catch(err:any){error.value=err.message||'仪表盘数据暂时不可用。'}});
</script>
<template><section class="home-dashboard" v-if="stats&&range"><div class="home-top"><div class="home-intro"><span class="eyebrow">CYBERQUEST / 训练总览</span><h1>{{greeting}}</h1><p>本地题目、练习会话与学习记录由后端统一保存。先从一项可验证的任务开始，而不是盲目刷题。</p><div class="home-actions"><RouterLink to="/challenges" class="primary-link">进入题目库 <i>→</i></RouterLink><RouterLink to="/learning" class="secondary-link">查看学习路径</RouterLink></div></div><aside class="today-panel"><header><span>今日训练</span><b>本地学习状态</b></header><div class="today-progress"><i :style="{width:Math.min(100,(range.metrics.completed/Math.max(1,stats.totalChallenges))*100)+'%'}"></i></div><div class="today-numbers"><span><b>{{range.metrics.completed}}</b> 已完成</span><span><b>{{range.metrics.availableTasks}}</b> 可开始</span></div><div class="today-note"><i></i>{{range.sessions.length?'当前有训练会话正在运行':'尚未启动训练会话'}}</div></aside></div><section class="home-stats"><article><span>训练任务</span><b>{{stats.totalChallenges}}</b><small>已在本地题库开放</small></article><article><span>有效提交</span><b>{{stats.totalSolves}}</b><small>包含正确答案记录</small></article><article><span>运行会话</span><b>{{range.metrics.activeSessions}}</b><small>当前账号的受控会话</small></article><article><span>练习材料</span><b>{{range.metrics.attachments}}</b><small>可下载的任务附件</small></article></section><div class="home-main"><section class="next-board"><header><div><span class="eyebrow">继续训练</span><h2>推荐下一步</h2></div><RouterLink to="/challenges">全部题目 →</RouterLink></header><div class="next-list"><RouterLink v-for="task in nextTasks" :key="task.id" :to="`/challenges/${task.slug}`" class="next-task"><span class="task-category">{{category[task.category]}}</span><div><h3>{{task.title}}</h3><p>{{task.description}}</p></div><b>{{task.points}}<small>分</small></b><i>→</i></RouterLink><div v-if="!nextTasks.length" class="home-empty">暂无新的可开始任务，完成前置训练或查看公开题源。</div></div></section><aside class="home-side"><section class="activity-card"><header><span class="eyebrow">近期活动</span><RouterLink to="/leaderboard">排行榜</RouterLink></header><div v-if="events.length" v-for="event in events.slice(0,4)" :key="event.createdAt" class="activity-line"><i></i><div><b>{{event.username||'平台'}}</b><p>{{event.message||event.type}}</p></div><time>{{new Date(event.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}}</time></div><p v-else class="quiet">暂无学习动态。</p></section><section class="rank-card"><header><span class="eyebrow">积分排行</span><RouterLink to="/leaderboard">查看全部</RouterLink></header><div v-for="user in ranking.slice(0,3)" :key="user.id" class="rank-line"><b>{{String(user.rank).padStart(2,'0')}}</b><span>{{user.username}}</span><small>{{user.score}} 分</small></div></section></aside></div></section><section v-else class="home-dashboard home-loading"><p v-if="error">{{error}}</p><p v-else>正在读取训练仪表盘…</p></section></template>
