<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { api } from './api';
import { useAuth } from './stores/auth';
const auth=useAuth(), data=ref<any>(), error=ref(''), working=ref('');
const category:any={WEB:'网页安全',CRYPTO:'密码学',NETWORK:'网络分析',REVERSE:'逆向工程',PWN:'二进制安全'};
const hasSession=computed(()=>data.value?.sessions?.length>0);
async function load(){try{error.value='';data.value=await api('/range/overview')}catch(e:any){error.value=e.message||'训练环境暂不可用。'}}
onMounted(load);
async function start(task:any){if(!auth.token){error.value='登录后才能创建个人训练会话。';return}working.value=task.slug;try{await api('/labs/start',{method:'POST',body:JSON.stringify({challengeId:task.slug})});await load()}catch(e:any){error.value=e.message}finally{working.value=''}}
</script>
<template><section class="experience" v-if="data"><div class="experience-heading"><div><span class="eyebrow">RANGE / 本地受控训练</span><h1>把每一次练习<br>留在可控范围内</h1><p>每个会话由后端按账号记录。这里展示真实可用任务与当前会话，而不是虚构的在线主机数量。</p></div><div class="command-panel"><span>训练环境状态</span><b>{{hasSession?'有会话正在运行':'等待启动'}}</b><p>{{hasSession?'可回到工作台继续观察':'从下方任务选择一个练习'}}</p><RouterLink to="/challenges" class="dark-action">浏览题目库 <i>→</i></RouterLink></div></div><div class="metric-row"><article><span>可开始任务</span><b>{{data.metrics.availableTasks}}</b><small>已通过前置条件</small></article><article><span>运行中会话</span><b>{{data.metrics.activeSessions}}</b><small>当前账号下的本地记录</small></article><article><span>已完成任务</span><b>{{data.metrics.completed}}</b><small>会计入能力与排行榜</small></article><article><span>材料附件</span><b>{{data.metrics.attachments}}</b><small>按题目下载与使用</small></article></div><div class="experience-grid"><section class="session-board"><header><div><span class="eyebrow">可用任务</span><h2>从任务库启动练习</h2></div><RouterLink to="/challenges">查看全部</RouterLink></header><article v-for="task in data.tasks" :key="task.id" class="task-line"><div class="line-icon">{{category[task.category]?.slice(0,1)}}</div><div><small>{{category[task.category]}} · {{task.difficulty}}</small><h3>{{task.title}}</h3><p>{{task.description}}</p></div><div class="line-points"><b>{{task.points}}</b><span>积分</span></div><button @click="start(task)" :disabled="working===task.slug">{{working===task.slug?'启动中':'启动会话'}}</button></article></section><aside class="current-session"><span class="eyebrow">我的会话</span><div v-if="data.sessions.length" v-for="session in data.sessions" :key="session.instanceId" class="live-session"><i></i><small>{{category[session.category]}}</small><h3>{{session.title}}</h3><p>剩余约 {{session.expiresInMinutes}} 分钟</p><RouterLink :to="`/challenges/${session.slug}`">前往任务</RouterLink></div><div v-else class="empty-session"><b>暂无进行中的会话</b><p>启动后会显示有效期与当前学习目标。不会自动创建容器或扫描外部网络。</p></div><div class="range-rule"><b>使用边界</b><p>只对题目提供的材料和链接进行操作；公开外部题源会在新窗口中打开。</p></div></aside></div></section><section v-else class="experience loading"><p v-if="error">{{error}}</p><p v-else>正在读取训练环境状态…</p></section></template>
